### PR TITLE
Added claps feature

### PR DESCRIPTION
**Pull request by Aditya-ds-1806**
## I ensure I have done the following steps

- [x] Star the repository :star:
- [x] Tested the code properly :white_check_mark:
- [x] Followed the [author](https://github.com/piyush97):white_check_mark:
- [x] Added the required feature :white_check_mark:

I am a complete noob when it comes to react and gatsby. In fact this is my first experience with it. I had to really go through the code and understand how things work, read documentation etc. If there are any mistakes, please forgive me. I would be happy to get your feedback!

### CODE REVIEW

**Comment by piyush97** [comment]
@Aditya-ds-1806 Thanks for making the feature, but it'd be great if you could persist the likes count for the https://github.com/ColinEberhardt/applause-button component. You can store it in faunaDb if required. 
Thanks

**Comment by piyush97** [comment]
@Aditya-ds-1806 You'll get hacktoberfest contribution for my repository only if it gets approved :)

**Comment by Aditya-ds-1806** [comment]
Applause-button does persist the like count as per the docs

**Comment by Aditya-ds-1806** [comment]
> 
> 
> @Aditya-ds-1806 You'll get hacktoberfest contribution for my repository only if it gets approved :)

Yes I understand, but hacktoberfest organisers changed the rules slightly. As per the new rules, only those repos that have the hacktoberfest badge will participate and only PRs to these repos will be accepted.
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by piyush97** [comment]
Please persist the number of likes in any db or cdn :)

**Comment by Aditya-ds-1806** [comment]
I'm not sure what you mean. The applause-button docs clearly state that "applause-button automatically persists the number of 'claps' given on a page using a simple cloud-hosted endpoint".

I don't see why you are asking me to create a separate database for storing the claps count, when applause-button is already doing that job for us. Can you please clarify?

**Pull request closed without merging**
